import type { PlayerArchetype, PlayerAttributes } from "../../../types/player";

/**
 * Base per-attribute cap targets by archetype before DNA/build modifiers are applied.
 *
 * Final caps are computed in the generator by layering potential, growth curve, frame,
 * position, and body-preset bonuses on top of these values.
 */
export const ARCHETYPE_BASE_CAPS: Record<PlayerArchetype, PlayerAttributes> = {
  Slasher: {
    shortRange: 94,
    dunking: 95,
    midrange: 74,
    threePoint: 82,
    handle: 88,
    passing: 86,
    vision: 86,
    perimeterDefense: 85,
    interiorDefense: 84,
    stealing: 89,
    blocking: 90,
    offRebounding: 66,
    defRebounding: 82,
    speed: 95,
    strength: 95,
    stamina: 90,
  },
  Sharpshooter: {
    shortRange: 80,
    dunking: 80,
    midrange: 87,
    threePoint: 97,
    handle: 84,
    passing: 84,
    vision: 88,
    perimeterDefense: 80,
    interiorDefense: 79,
    stealing: 81,
    blocking: 81,
    offRebounding: 62,
    defRebounding: 78,
    speed: 82,
    strength: 81,
    stamina: 88,
  },
  Playmaker: {
    shortRange: 82,
    dunking: 83,
    midrange: 79,
    threePoint: 88,
    handle: 97,
    passing: 97,
    vision: 90,
    perimeterDefense: 82,
    interiorDefense: 80,
    stealing: 84,
    blocking: 84,
    offRebounding: 59,
    defRebounding: 74,
    speed: 86,
    strength: 84,
    stamina: 90,
  },
  "Lockdown Defender": {
    shortRange: 82,
    dunking: 84,
    midrange: 72,
    threePoint: 80,
    handle: 82,
    passing: 83,
    vision: 90,
    perimeterDefense: 97,
    interiorDefense: 95,
    stealing: 94,
    blocking: 94,
    offRebounding: 72,
    defRebounding: 90,
    speed: 90,
    strength: 86,
    stamina: 92,
  },
  "Paint Beast": {
    shortRange: 94,
    dunking: 93,
    midrange: 63,
    threePoint: 70,
    handle: 72,
    passing: 76,
    vision: 86,
    perimeterDefense: 92,
    interiorDefense: 97,
    stealing: 91,
    blocking: 94,
    offRebounding: 80,
    defRebounding: 98,
    speed: 86,
    strength: 94,
    stamina: 90,
  },
  "Stretch Big": {
    shortRange: 86,
    dunking: 85,
    midrange: 83,
    threePoint: 92,
    handle: 76,
    passing: 80,
    vision: 88,
    perimeterDefense: 88,
    interiorDefense: 89,
    stealing: 86,
    blocking: 85,
    offRebounding: 74,
    defRebounding: 92,
    speed: 82,
    strength: 84,
    stamina: 90,
  },
};
