import type { PlayerArchetype, PlayerAttributes } from "../../../types/player";

export const ARCHETYPE_BASE_CAPS: Record<PlayerArchetype, PlayerAttributes> = {
  Slasher: {
    shooting: 82,
    finishing: 94,
    vision: 84,
    handle: 88,
    athleticism: 95,
    defense: 85,
    rebounding: 82,
    bbiq: 86,
    stamina: 90,
  },
  Sharpshooter: {
    shooting: 97,
    finishing: 80,
    vision: 84,
    handle: 84,
    athleticism: 82,
    defense: 80,
    rebounding: 78,
    bbiq: 88,
    stamina: 88,
  },
  Playmaker: {
    shooting: 88,
    finishing: 82,
    vision: 97,
    handle: 97,
    athleticism: 86,
    defense: 82,
    rebounding: 74,
    bbiq: 90,
    stamina: 90,
  },
  "Lockdown Defender": {
    shooting: 80,
    finishing: 82,
    vision: 84,
    handle: 82,
    athleticism: 90,
    defense: 97,
    rebounding: 90,
    bbiq: 90,
    stamina: 92,
  },
  "Paint Beast": {
    shooting: 70,
    finishing: 94,
    vision: 78,
    handle: 72,
    athleticism: 88,
    defense: 94,
    rebounding: 97,
    bbiq: 86,
    stamina: 90,
  },
  "Stretch Big": {
    shooting: 92,
    finishing: 86,
    vision: 82,
    handle: 76,
    athleticism: 82,
    defense: 88,
    rebounding: 92,
    bbiq: 88,
    stamina: 90,
  },
};
