import type { PlayerArchetype, PlayerAttributes } from "../types/player";

export const ARCHETYPE_DEFAULTS: Record<PlayerArchetype, PlayerAttributes> = ({
  Slasher: {
    shortRange: 68,
    dunking: 71,
    midrange: 41,
    threePoint: 45,
    handle: 58,
    passing: 51,
    vision: 48,
    perimeterDefense: 42,
    interiorDefense: 43,
    stealing: 53,
    blocking: 56,
    offRebounding: 35,
    defRebounding: 44,
    speed: 71,
    strength: 69,
    stamina: 62,
  },
  Sharpshooter: {
    shortRange: 46,
    dunking: 46,
    midrange: 62,
    threePoint: 72,
    handle: 52,
    passing: 51,
    vision: 52,
    perimeterDefense: 38,
    interiorDefense: 39,
    stealing: 42,
    blocking: 43,
    offRebounding: 32,
    defRebounding: 40,
    speed: 48,
    strength: 47,
    stamina: 58,
  },
  Playmaker: {
    shortRange: 48,
    dunking: 50,
    midrange: 47,
    threePoint: 52,
    handle: 72,
    passing: 71,
    vision: 58,
    perimeterDefense: 42,
    interiorDefense: 41,
    stealing: 48,
    blocking: 49,
    offRebounding: 30,
    defRebounding: 38,
    speed: 56,
    strength: 52,
    stamina: 60,
  },
  "Lockdown Defender": {
    shortRange: 48,
    dunking: 50,
    midrange: 38,
    threePoint: 42,
    handle: 50,
    passing: 50,
    vision: 56,
    perimeterDefense: 72,
    interiorDefense: 68,
    stealing: 66,
    blocking: 65,
    offRebounding: 48,
    defRebounding: 60,
    speed: 58,
    strength: 53,
    stamina: 64,
  },
  "Paint Beast": {
    shortRange: 66,
    dunking: 64,
    midrange: 32,
    threePoint: 35,
    handle: 38,
    passing: 40,
    vision: 50,
    perimeterDefense: 60,
    interiorDefense: 67,
    stealing: 58,
    blocking: 63,
    offRebounding: 60,
    defRebounding: 74,
    speed: 54,
    strength: 64,
    stamina: 66,
  },
  "Stretch Big": {
    shortRange: 54,
    dunking: 52,
    midrange: 60,
    threePoint: 66,
    handle: 44,
    passing: 46,
    vision: 54,
    perimeterDefense: 54,
    interiorDefense: 60,
    stealing: 50,
    blocking: 53,
    offRebounding: 52,
    defRebounding: 66,
    speed: 45,
    strength: 52,
    stamina: 60,
  },
} as any); // TODO: Sprint 2 - remove cast when legacy match-engine keys are deleted
