import type { PlayerArchetype, PlayerAttributes } from "../types/player";

export const ARCHETYPE_DEFAULTS: Record<PlayerArchetype, PlayerAttributes> = {
  Slasher: {
    shooting: 45,
    finishing: 68,
    vision: 46,
    handle: 58,
    athleticism: 70,
    defense: 42,
    rebounding: 44,
    bbiq: 48,
    stamina: 62,
  },
  Sharpshooter: {
    shooting: 70,
    finishing: 46,
    vision: 50,
    handle: 52,
    athleticism: 48,
    defense: 38,
    rebounding: 40,
    bbiq: 52,
    stamina: 58,
  },
  Playmaker: {
    shooting: 52,
    finishing: 48,
    vision: 70,
    handle: 72,
    athleticism: 56,
    defense: 42,
    rebounding: 38,
    bbiq: 58,
    stamina: 60,
  },
  "Lockdown Defender": {
    shooting: 42,
    finishing: 48,
    vision: 50,
    handle: 50,
    athleticism: 58,
    defense: 72,
    rebounding: 60,
    bbiq: 56,
    stamina: 64,
  },
  "Paint Beast": {
    shooting: 35,
    finishing: 66,
    vision: 42,
    handle: 38,
    athleticism: 56,
    defense: 62,
    rebounding: 72,
    bbiq: 50,
    stamina: 66,
  },
  "Stretch Big": {
    shooting: 64,
    finishing: 54,
    vision: 48,
    handle: 44,
    athleticism: 46,
    defense: 56,
    rebounding: 64,
    bbiq: 54,
    stamina: 60,
  },
};
