"use strict";

module.exports = {
  minEventSeconds: 7,
  maxEventSeconds: 24,
  turnoverEventSecondsMin: 5,
  turnoverEventSecondsMax: 11,
  offensiveReboundEventSecondsMin: 4,
  offensiveReboundEventSecondsMax: 8,
  archetypeWeightAdjustments: {
    Slasher: { pass: 0, shoot: 10, dribble: 18 },
    Sharpshooter: { pass: 3, shoot: 20, dribble: -5 },
    Playmaker: { pass: 18, shoot: -4, dribble: 8 },
    "Lockdown Defender": { pass: 8, shoot: -5, dribble: 4 },
    "Paint Beast": { pass: 2, shoot: 12, dribble: -8 },
    "Stretch Big": { pass: 4, shoot: 14, dribble: -6 },
  },
  baseActionWeights: { pass: 34, shoot: 38, dribble: 28 },
  highPressureAdjustments: { pass: 8, shoot: 10, dribble: -6 },
  lowPressureAdjustments: { pass: 0, shoot: 0, dribble: 0 },
  // Home-court edge is intentionally subtle. Target roughly +0.5-2.0% home win rate for evenly matched teams.
  // shotMultiplier affects shot and putback make probabilities (light-touch tuning range: 1.00-1.03).
  // turnoverMultiplier affects turnover probability (home reduced, away inverse increased; light-touch range: 0.99-1.00).
  homeCourt: {
    enabled: true,
    shotMultiplier: 1.005,
    turnoverMultiplier: 0.995,
  },
  // Momentum is intentionally subtle and deterministic.
  // Streak 1: +/-0.8%, streak 2: +/-1.6%, streak 3: +/-2.4%, streak 4: +/-3.2%, streak 5+: capped at +/-4.0%.
  momentum: {
    enabled: false,
    maxStreak: 5,
    perMakeBoost: 0.008,
    perMakePenalty: 0.008,
  },
  turnoverBase: 0.09,
  turnoverDivisor: 540,
  turnoverMin: 0.04,
  turnoverMax: 0.21,
  stealBase: 0.25,
  stealDivisor: 250,
  stealMin: 0.08,
  stealMax: 0.38,
  assistBase: 0.38,
  assistDivisor: 260,
  assistMin: 0.18,
  assistMax: 0.75,
  shotZoneByAction: {
    pass: { three: 0.37, midrange: 0.22, rim: 0.41 },
    shoot: { three: 0.35, midrange: 0.35, rim: 0.3 },
    dribble: { three: 0.13, midrange: 0.28, rim: 0.59 },
  },
  lowShootingThreeSuppressionThreshold: 40,
  shotZoneSkillWeight: 0.12,
  shotZoneBbiqWeight: 0.1,
  shotZoneFatigueWeight: 0.08,
  shotMakeBase: 0.02,
  shotMakeMin: 0.31,
  shotMakeMax: 0.72,
  threeShotMakeBase: 0.29,
  midrangeShotMakeBase: 0.37,
  rimShotMakeBase: 0.5,
  shotContestDivisor: 520,
  shotOffenseDivisor: 180,
  blockBase: 0.06,
  blockDivisor: 420,
  blockMin: 0.01,
  blockMax: 0.16,
  offensiveReboundBase: 0.18,
  offensiveReboundDivisor: 330,
  offensiveReboundMin: 0.1,
  offensiveReboundMax: 0.33,
  longReboundThreeBonus: 0.04,
  putbackBase: 0.36,
  putbackDivisor: 330,
  putbackMin: 0.29,
  putbackMax: 0.66,
  fatiguePossessionScale: 0.0027,
  fatigueStaminaOffset: 55,
  fatigueMinMultiplier: 0.68,
  fatigueMaxMultiplier: 1.05,
  decisionVarianceBase: 3,
  decisionVarianceBbiqScale: 7,
  energyModifierScale: 0.17,
  bbiqModifierScale: 0.13,
  threePointOffset: 35,
  threePointDivisor: 90,
  threePointMin: 0.12,
  threePointMax: 0.5,
};
