"use strict";

const makeAttributes = (overrides = {}) => ({
  shortRange: 60,
  dunking: 60,
  midrange: 60,
  threePoint: 60,
  handle: 60,
  passing: 60,
  vision: 60,
  perimeterDefense: 60,
  interiorDefense: 60,
  stealing: 60,
  blocking: 60,
  offRebounding: 60,
  defRebounding: 60,
  speed: 60,
  strength: 60,
  stamina: 60,
  ...overrides,
});

const makePlayer = (id, name, archetype, position, attributes, extras = {}) => ({
  id,
  name,
  age: 19,
  bankBalance: extras.bankBalance ?? 0,
  morale: extras.morale ?? 50,
  position,
  secondaryPosition: extras.secondaryPosition ?? "SG",
  archetype,
  identity: null,
  dna: null,
  attributes,
  gameStats: { points: 0, assists: 0, rebounds: 0, steals: 0, blocks: 0, fga: 0, fgm: 0 },
});

const createBaseContext = () => ({
  home: {
    name: "Metro State",
    teamOvr: 0,
    roster: [
      makePlayer("h1", "A1", "Playmaker", "PG", makeAttributes({
        shortRange: 66,
        dunking: 67,
        midrange: 63,
        threePoint: 70,
        handle: 84,
        passing: 83,
        vision: 78,
        perimeterDefense: 58,
        interiorDefense: 54,
        stealing: 65,
        blocking: 65,
        offRebounding: 35,
        defRebounding: 44,
        speed: 71,
        strength: 69,
        stamina: 80,
      })),
      makePlayer("h2", "A2", "Sharpshooter", "SG", makeAttributes({
        shortRange: 61,
        dunking: 62,
        midrange: 77,
        threePoint: 85,
        handle: 63,
        passing: 60,
        vision: 70,
        perimeterDefense: 54,
        interiorDefense: 52,
        stealing: 57,
        blocking: 59,
        offRebounding: 38,
        defRebounding: 47,
        speed: 64,
        strength: 63,
        stamina: 76,
      })),
      makePlayer("h3", "A3", "Slasher", "SF", makeAttributes({
        shortRange: 79,
        dunking: 80,
        midrange: 57,
        threePoint: 63,
        handle: 72,
        passing: 62,
        vision: 68,
        perimeterDefense: 66,
        interiorDefense: 64,
        stealing: 72,
        blocking: 74,
        offRebounding: 48,
        defRebounding: 60,
        speed: 81,
        strength: 80,
        stamina: 79,
      })),
      makePlayer("h4", "A4", "Stretch Big", "PF", makeAttributes({
        shortRange: 68,
        dunking: 66,
        midrange: 69,
        threePoint: 77,
        handle: 48,
        passing: 53,
        vision: 71,
        perimeterDefense: 70,
        interiorDefense: 71,
        stealing: 66,
        blocking: 65,
        offRebounding: 59,
        defRebounding: 74,
        speed: 60,
        strength: 64,
        stamina: 74,
      })),
      makePlayer("h5", "A5", "Paint Beast", "C", makeAttributes({
        shortRange: 83,
        dunking: 79,
        midrange: 47,
        threePoint: 52,
        handle: 41,
        passing: 44,
        vision: 69,
        perimeterDefense: 79,
        interiorDefense: 81,
        stealing: 71,
        blocking: 72,
        offRebounding: 69,
        defRebounding: 86,
        speed: 65,
        strength: 74,
        stamina: 72,
      })),
    ],
  },
  away: {
    name: "Central Tech",
    teamOvr: 0,
    roster: [
      makePlayer("a1", "B1", "Playmaker", "PG", makeAttributes({
        shortRange: 64,
        dunking: 65,
        midrange: 61,
        threePoint: 68,
        handle: 81,
        passing: 80,
        vision: 76,
        perimeterDefense: 57,
        interiorDefense: 53,
        stealing: 62,
        blocking: 64,
        offRebounding: 34,
        defRebounding: 43,
        speed: 70,
        strength: 67,
        stamina: 79,
      })),
      makePlayer("a2", "B2", "Sharpshooter", "SG", makeAttributes({
        shortRange: 59,
        dunking: 60,
        midrange: 74,
        threePoint: 82,
        handle: 61,
        passing: 58,
        vision: 68,
        perimeterDefense: 53,
        interiorDefense: 50,
        stealing: 56,
        blocking: 58,
        offRebounding: 36,
        defRebounding: 45,
        speed: 63,
        strength: 61,
        stamina: 75,
      })),
      makePlayer("a3", "B3", "Lockdown Defender", "SF", makeAttributes({
        shortRange: 72,
        dunking: 73,
        midrange: 55,
        threePoint: 61,
        handle: 67,
        passing: 58,
        vision: 72,
        perimeterDefense: 81,
        interiorDefense: 76,
        stealing: 80,
        blocking: 79,
        offRebounding: 51,
        defRebounding: 64,
        speed: 77,
        strength: 75,
        stamina: 81,
      })),
      makePlayer("a4", "B4", "Stretch Big", "PF", makeAttributes({
        shortRange: 66,
        dunking: 65,
        midrange: 67,
        threePoint: 74,
        handle: 45,
        passing: 55,
        vision: 70,
        perimeterDefense: 72,
        interiorDefense: 73,
        stealing: 65,
        blocking: 66,
        offRebounding: 61,
        defRebounding: 76,
        speed: 59,
        strength: 63,
        stamina: 73,
      })),
      makePlayer("a5", "B5", "Paint Beast", "C", makeAttributes({
        shortRange: 81,
        dunking: 77,
        midrange: 45,
        threePoint: 50,
        handle: 39,
        passing: 42,
        vision: 68,
        perimeterDefense: 80,
        interiorDefense: 82,
        stealing: 69,
        blocking: 72,
        offRebounding: 68,
        defRebounding: 85,
        speed: 63,
        strength: 72,
        stamina: 71,
      })),
    ],
  },
});

const cloneContext = (context) => ({
  home: {
    ...context.home,
    roster: context.home.roster.map((player) => ({
      ...player,
      dna: player.dna
        ? {
            ...player.dna,
            caps: { ...player.dna.caps },
            growthResidue: { ...player.dna.growthResidue },
            publicTraits: [...player.dna.publicTraits],
            builderProfile: player.dna.builderProfile
              ? {
                  ...player.dna.builderProfile,
                  classification: {
                    ...player.dna.builderProfile.classification,
                    taxonomy: { ...player.dna.builderProfile.classification.taxonomy },
                    topStrengths: [...player.dna.builderProfile.classification.topStrengths],
                  },
                  badges: player.dna.builderProfile.badges.map((badge) => ({ ...badge })),
                }
              : player.dna.builderProfile,
          }
        : null,
      attributes: { ...player.attributes },
      gameStats: { ...player.gameStats },
    })),
  },
  away: {
    ...context.away,
    roster: context.away.roster.map((player) => ({
      ...player,
      dna: player.dna
        ? {
            ...player.dna,
            caps: { ...player.dna.caps },
            growthResidue: { ...player.dna.growthResidue },
            publicTraits: [...player.dna.publicTraits],
            builderProfile: player.dna.builderProfile
              ? {
                  ...player.dna.builderProfile,
                  classification: {
                    ...player.dna.builderProfile.classification,
                    taxonomy: { ...player.dna.builderProfile.classification.taxonomy },
                    topStrengths: [...player.dna.builderProfile.classification.topStrengths],
                  },
                  badges: player.dna.builderProfile.badges.map((badge) => ({ ...badge })),
                }
              : player.dna.builderProfile,
          }
        : null,
      attributes: { ...player.attributes },
      gameStats: { ...player.gameStats },
    })),
  },
});

const createEvenContext = () => {
  const base = createBaseContext();
  const homeRoster = base.home.roster.map((player, index) => ({
    ...player,
    id: `eq-h${index + 1}`,
    name: `Even Home ${index + 1}`,
    attributes: { ...player.attributes },
    gameStats: { ...player.gameStats },
  }));
  const awayRoster = homeRoster.map((player, index) => ({
    ...player,
    id: `eq-a${index + 1}`,
    name: `Even Away ${index + 1}`,
    gameStats: { ...player.gameStats },
  }));

  return {
    home: { ...base.home, roster: homeRoster },
    away: { ...base.away, name: "Even Away", roster: awayRoster },
  };
};

module.exports = {
  makeAttributes,
  makePlayer,
  createBaseContext,
  createEvenContext,
  cloneContext,
};
